/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 earth.gltf 
Author: Huntrezz.Janos (https://sketchfab.com/Huntrezz)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/story-object-pl-anet-f098f910a88442268d223bc20ea9a70c
Title: STORY OBJECT Pl ANET
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/earth.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0.981, 0.822, 1.353]} scale={1}>
        <mesh geometry={nodes.Object_4.geometry} material={materials['defaultMat.001']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['DS1_tex_01.001']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['lightergrey.001']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['Gold.001']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['DS1_tex_01.003']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['DS1_tex_01.002']} />
        <mesh geometry={nodes.Object_10.geometry} material={materials['lightergrey.003']} />
        <mesh geometry={nodes.Object_11.geometry} material={materials['lightergrey.002']} />
        <mesh geometry={nodes.Object_12.geometry} material={materials['Gold.003']} />
        <mesh geometry={nodes.Object_13.geometry} material={materials['Gold.002']} />
        <mesh geometry={nodes.Object_14.geometry} material={materials['DS1_tex_01.007']} />
        <mesh geometry={nodes.Object_15.geometry} material={materials['DS1_tex_01.006']} />
        <mesh geometry={nodes.Object_16.geometry} material={materials['DS1_tex_01.005']} />
        <mesh geometry={nodes.Object_17.geometry} material={materials['DS1_tex_01.004']} />
        <mesh geometry={nodes.Object_18.geometry} material={materials['lightergrey.007']} />
        <mesh geometry={nodes.Object_19.geometry} material={materials['lightergrey.006']} />
        <mesh geometry={nodes.Object_20.geometry} material={materials['lightergrey.005']} />
        <mesh geometry={nodes.Object_21.geometry} material={materials['lightergrey.004']} />
        <mesh geometry={nodes.Object_22.geometry} material={materials['Gold.007']} />
        <mesh geometry={nodes.Object_23.geometry} material={materials['Gold.006']} />
        <mesh geometry={nodes.Object_24.geometry} material={materials['Gold.005']} />
        <mesh geometry={nodes.Object_25.geometry} material={materials['Gold.004']} />
        <mesh geometry={nodes.Object_26.geometry} material={materials['Material_0.005']} />
        <mesh geometry={nodes.Object_27.geometry} material={materials['Material_0.007']} />
        <mesh geometry={nodes.Object_28.geometry} material={materials['Material_0.006']} />
        <mesh geometry={nodes.Object_29.geometry} material={materials['Material_0.011']} />
        <mesh geometry={nodes.Object_30.geometry} material={materials['Material_0.010']} />
        <mesh geometry={nodes.Object_31.geometry} material={materials['Material_0.009']} />
        <mesh geometry={nodes.Object_32.geometry} material={materials['Material_0.008']} />
        <mesh geometry={nodes.Object_33.geometry} material={materials['Material_0.019']} />
        <mesh geometry={nodes.Object_34.geometry} material={materials['Material_0.018']} />
        <mesh geometry={nodes.Object_35.geometry} material={materials['Material_0.017']} />
        <mesh geometry={nodes.Object_36.geometry} material={materials['Material_0.016']} />
        <mesh geometry={nodes.Object_37.geometry} material={materials['Material_0.015']} />
        <mesh geometry={nodes.Object_38.geometry} material={materials['Material_0.014']} />
        <mesh geometry={nodes.Object_39.geometry} material={materials['Material_0.013']} />
        <mesh geometry={nodes.Object_40.geometry} material={materials['Material_0.012']} />
        <mesh geometry={nodes.Object_41.geometry} material={materials['Material_0.035']} />
        <mesh geometry={nodes.Object_42.geometry} material={materials['Material_0.034']} />
        <mesh geometry={nodes.Object_43.geometry} material={materials['Material_0.033']} />
        <mesh geometry={nodes.Object_44.geometry} material={materials['Material_0.032']} />
        <mesh geometry={nodes.Object_45.geometry} material={materials['Material_0.031']} />
        <mesh geometry={nodes.Object_46.geometry} material={materials['Material_0.030']} />
        <mesh geometry={nodes.Object_47.geometry} material={materials['Material_0.029']} />
        <mesh geometry={nodes.Object_48.geometry} material={materials['Material_0.028']} />
        <mesh geometry={nodes.Object_49.geometry} material={materials['Material_0.027']} />
        <mesh geometry={nodes.Object_50.geometry} material={materials['Material_0.026']} />
        <mesh geometry={nodes.Object_51.geometry} material={materials['Material_0.025']} />
        <mesh geometry={nodes.Object_52.geometry} material={materials['Material_0.024']} />
        <mesh geometry={nodes.Object_53.geometry} material={materials['Material_0.023']} />
        <mesh geometry={nodes.Object_54.geometry} material={materials['Material_0.022']} />
        <mesh geometry={nodes.Object_55.geometry} material={materials['Material_0.021']} />
        <mesh geometry={nodes.Object_56.geometry} material={materials['Material_0.020']} />
        <mesh geometry={nodes.Object_57.geometry} material={materials['defaultMat.004']} />
        <mesh geometry={nodes.Object_58.geometry} material={materials['defaultMat.005']} />
        <mesh geometry={nodes.Object_59.geometry} material={materials['defaultMat.006']} />
        <mesh geometry={nodes.Object_60.geometry} material={materials['defaultMat.007']} />
        <mesh geometry={nodes.Object_61.geometry} material={materials['defaultMat.008']} />
        <mesh geometry={nodes.Object_62.geometry} material={materials['defaultMat.009']} />
        <mesh geometry={nodes.Object_63.geometry} material={materials['defaultMat.010']} />
        <mesh geometry={nodes.Object_64.geometry} material={materials.Earth} />
        <mesh geometry={nodes.Object_65.geometry} material={materials['Material_0.001']} />
        <mesh geometry={nodes.Object_66.geometry} material={materials['Material_0.003']} />
        <mesh geometry={nodes.Object_67.geometry} material={materials.lightergrey} />
        <mesh geometry={nodes.Object_68.geometry} material={materials.Gold} />
        <mesh geometry={nodes.Object_69.geometry} material={materials.DS1_tex_01} />
      </group>
    </group>
  )
}

useGLTF.preload('/earth.gltf')
